apiVersion: v1
kind: Pod
metadata:
  name: lines-admin-nextjs
  labels:
    name: lines-admin-nextjs
spec:
  containers:
  - name: lines-admin-nextjs
    image: gcr.io/lines-infra/lines_admin_front:v1.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
