apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: lines-admin-nextjs-replicaset
  labels:
    app: lines-admin-nextjs
    tier: lines-admin-nextjs
spec:
  # modify replicas according to your case
  replicas: 2
  selector: # 키와 값이 같아야 설정할수 있게 처리, matchExpressions 에는 key, operator ( Exists, DoesNotExist, In, NotIn )를 설정할 수 있음
    matchLabels:
      tier: lines-admin-nextjs
  template: # 서비스가 장애가 나거나 정상적으로 동작하지 않을 때 Template 으로 사용이 가능하다.
    metadata:
      labels:
        tier: lines-admin-nextjs
    spec:
      containers:
        - name: lines-admin-nextjs
          image: gcr.io/lines-infra/lines_admin_front:v0.1.0