apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: cj2
spec: {}
status: {}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: cjob
  namespace: cj2
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: cjob
    spec:
      template:
        metadata:
        spec:
          containers:
            - image: busybox
              name: cjob
              command:
              resources: {}
              args:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
  schedule: "*/1 * * * *"
status: {}